markdown: rdiscount
pygments: true
exclude: Gemfile, Gemfile.lock, Procfile, Rakefile, Readme, config.rb, sass
permalink: :title

# Site configuration
baseurl: /
url: http://yoga-rathgeber.de
domain: yoga-rathgeber.de
title: Yoga im Aischgrund
subtitle: Gabriele Rathgeber - Yogalehrerin BDY/EYU
author: Gabriele Rathgeber
email: gabriele.rathgeber@gmail.com
feedurl: atom.xml
analytics_id: UA-xxxxxxxx-x
