markdown: rdiscount
pygments: true
exclude: Gemfile, Gemfile.lock, Procfile, Rakefile, Readme, config.rb, sass
permalink: :title

# Site configuration
baseurl: /
url: http://yoga-rathgeber.de
domain: yoga-rathgeber.de
title: Gabi Rathgeber - Yogalehrerin BDY/EYU
subtitle: Yoga im Aischgrund
author: Gabriele Rathgeber
email: gabi@yoga-rathgeber.de
feedurl: atom.xml
analytics_id: UA-xxxxxxxx-x
