markdown: rdiscount
pygments: true
exclude: Gemfile, Gemfile.lock, Procfile, Rakefile, Readme, config.rb, sass
permalink: :title

# Site configuration
baseurl: /
url: http://johndoe.com
domain: johndoe.com
title: John Doe's Blog
author: John Doe
email: me@johndoe.com
feedurl: atom.xml
analytics_id: UA-xxxxxxxx-x
