markdown: rdiscount
pygments: true
exclude: Gemfile, Gemfile.lock, Procfile, Rakefile, Readme, config.rb, sass

# Site configuration
baseurl: /
domain: johndoe.com
title: John Doe's Blog
author: John Doe
email: me@johndoe.com
feedurl: http://johndoe.com/atom.xml
analytics_id: UA-xxxxxxxx-x
